name: 'Test'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:

  # Only checking latest Linux/UNIX on pulls to save execution times
  test-master-pulls:
    if: github.event_name == 'pull_request'
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - 'macos-latest'
          - 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Run all tests'
        run: './test/run.sh'
        shell: 'bash'

  # When we push to master, test everything in order to guarantee releases
  test-master-pushes:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          # - 'macos-11.0' # Not yet available
          - 'macos-10.15'
          - 'ubuntu-20.04'
          - 'ubuntu-18.04'
          - 'windows-2019'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Run all tests'
        run: './test/run.sh'
        shell: 'bash'
